CREATE TABLE `USER_ACCOUNTS` (
  `ID`        INT(10)      NOT NULL AUTO_INCREMENT,
  `EMAIL` VARCHAR(200) NOT NULL,
  `PASSWORD`  VARCHAR(200) NOT NULL,
  `FIRSTNAME` VARCHAR(50)  NOT NULL,
  `LASTNAME`  VARCHAR(50)  NOT NULL,
  `STATUS`    VARCHAR(10)  NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID` (`ID`, `EMAIL`)
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8;